version: "3"

tasks:
  import-obsidian:
    desc: Reimport obsidian file collection into weaviate
    cmds:
      - ./weaviate/import_obsidian.sh -d /home/fritz/Sync/FritzSync/private -b /home/fritz/Sync/
